apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: computateorg
    app.kubernetes.io/instance: computateorg
    app.kubernetes.io/name: computateorg
    deployment: computateorg
  name: computateorg
  namespace: computateorg
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: computateorg
      app.kubernetes.io/instance: computateorg
      app.kubernetes.io/name: computateorg
      deployment: computateorg
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: computateorg
        app.kubernetes.io/instance: computateorg
        app.kubernetes.io/name: computateorg
        deployment: computateorg
    spec:
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: git-cloner
          command:
            - sh
            - '-c'
          imagePullPolicy: Always
          volumeMounts:
            - name: "smart-aquaculture-developer"
              mountPath: "/home/default/computate.org-static/webawesome/templates/en-us/smart-aquaculture-developer"
            - name: "ai-telemetry-developer"
              mountPath: "/home/default/computate.org-static/webawesome/templates/en-us/ai-telemetry-developer"
            - name: "computate-developer"
              mountPath: "/home/default/computate.org-static/webawesome/templates/en-us/computate-developer"
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: cloud-extra
          image: docker.io/alpine/git
          args:
            - >-
              git clone https://computate.org:$GITHUB_DEVELOPERS_TOKEN@github.com/computate-org/smart-aquaculture-developer.git /home/default/computate.org-static/webawesome/templates/en-us/smart-aquaculture-developer; 
              git clone https://computate.org:$GITHUB_DEVELOPERS_TOKEN@github.com/computate-org/ai-telemetry-developer.git /home/default/computate.org-static/webawesome/templates/en-us/ai-telemetry-developer; 
              git clone https://computate.org:$GITHUB_DEVELOPERS_TOKEN@github.com/computate-org/computate-developer.git /home/default/computate.org-static/webawesome/templates/en-us/computate-developer; 
      containers:
      - name: computateorg
        env:
          - name: ENABLE_ZOOKEEPER_CLUSTER
            value: 'true'
          - name: CLUSTER_HOST_NAME
            value: 0.0.0.0
          - name: CLUSTER_PORT
            value: '10201'
          - name: CLUSTER_PUBLIC_HOST_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: CLUSTER_PUBLIC_PORT
            value: '10201'
        envFrom:
        - secretRef:
            name: cloud-zookeeper
        - secretRef:
            name: cloud-solr
        - secretRef:
            name: cloud-database
        - secretRef:
            name: cloud-auth
        - secretRef:
            name: cloud-context-broker
        - secretRef:
            name: cloud-site
        - secretRef:
            name: cloud-font-awesome
        - secretRef:
            name: cloud-extra
        image: quay.io/computateorg/computate.org:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 10
        ports:
        - containerPort: 10200
          name: http
          protocol: TCP
        - containerPort: 10201
          name: cluster
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 768Mi
          requests:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 768Mi
          volumeMounts:
            - name: "smart-aquaculture-developer"
              mountPath: "/home/default/computate.org-static/webawesome/templates/en-us/smart-aquaculture-developer"
            - name: "ai-telemetry-developer"
              mountPath: "/home/default/computate.org-static/webawesome/templates/en-us/ai-telemetry-developer"
            - name: "computate-developer"
              mountPath: "/home/default/computate.org-static/webawesome/templates/en-us/computate-developer"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: "smart-aquaculture-developer"
          emptyDir: {}
        - name: "ai-telemetry-developer"
          emptyDir: {}
        - name: "computate-developer"
          emptyDir: {}
